### ISSUE TITLE
bme688 sample fails

### ISSUE THREAD

**Issue by mrdiogodias** [HomeSmartMesh/sdk-hsm-thingy53#1]
Hello,

I've tried to run the 05_bme688 sample but I have always the following output: 
`<err> bme688: API name [bme68x_get_data]  Warning [2] : No new data found`
Do you have any idea why?

And other question, why do you call bme688_init() in main? Since you're using the zephyr driver model, the init function will run before the main as you defined here:
`#define BME688_DEFINE(inst)                                                                                            
    static struct bme68x_data bme68x_data_##inst;                                                                      
    static const struct bme688_config bme688_config_##inst = BME688_CONFIG_I2C(inst);                                  
    DEVICE_DT_INST_DEFINE(inst, bme688_init, NULL, &bme68x_data_##inst, &bme688_config_##inst, POST_KERNEL, CONFIG_SENSOR_INIT_PRIORITY, &bme688_api_funcs);`

Thank you for your support!

**Comment by wassfila** [comment]
Hi,
can you check `06_bme688_parallel`, `07_bme688_parallel_cpp`, `08_bme688_bsec2` and `20_sensors_server`

I might have forgotten to update the 05 sample after modifying the driver for the sample 20. The sample 20 is the one I currently have running and deployed.

We can keep this issue open until I have a look, if I reproduce it I will fix it, otherwise troubleshoot with you.

Good point about init by the driver, I lost hope of having a fully compliant Zephyr driver due to the non existing interface for x10 gas values, it is also a habit of wanting to control exactly which driver start when, but I could rely on Zephyr for init it's true (if I manage to get it work )

**Comment by wassfila** [comment]
Fixed it, after updating the drivers to support parallel mode and BSEC2, I did not adjust the sequence for Forced mode.
Here the reference sequence
https://github.com/boschsensortec/BME68x-Sensor-API/blob/master/examples/forced_mode/forced_mode.c

it is important that calls from main for `bme688_init`, and then in the loop `bme688_sample_fetch` and `bme688_data_get` matche the reference calls.

I also simplified the data to be just one field instead of array and protected it in the `bme688_data_get` function

<img width="551" alt="image" src="https://github.com/HomeSmartMesh/sdk-hsm-thingy53/assets/1510763/49fe833e-5003-4402-9c48-7caff59733e6">

06_bme688_prarallel is also working
<img width="639" alt="image" src="https://github.com/HomeSmartMesh/sdk-hsm-thingy53/assets/1510763/6a18c9db-de27-4a10-934b-8db8604098b2">

**Comment by wassfila** [comment]
@mrdiogodias for info this is now fixed, and for info I do have a Discord server if you want to chat about what you do with the Thingy53, I'm running them now with a Linux border router and influxDB, Grafana,...
here an invite https://discord.gg/2J9rEEgvwM

**Comment by mrdiogodias** [comment]
Hello. 
I don't actually have a thingy53, I just wanted to use the bme688 with the bsec library and I was able to do so by converting your c++ code to c, so thank you for that. 
By the way, how do you calibrate your sensor? You just let it run and calibrate itself or you have a process? I'm asking because I let it run for like 20h and only after I pour some alcohol into it I was able to see the IAQ accuracy changing from 1 to 2 and then eventually to 3.

**Comment by wassfila** [comment]
I recommend to read both of "bst-bme688-an001.pdf" and "bst-bme688-ds000.pdf"
they mention 24h run on first use and how bsec uses history to autocalibrate, also that you expose it to best and worst conditions to help calib.
for technical questions related to the sensor not to the integration of the sw in this repo, I recommend searching in the vendor's forum https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/bd-p/bst_community-mems-forum it's full of similar questions and answers.

Cool that you managed to port the code to C, which microcontroller and compiler do you use then ? and what is your target application, a hobby or university project or to sell it as a product ?
